# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20171220_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='ip_address',
            new_name='certificate_id',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='certificate',
            new_name='ipaddress_id',
        ),
    ]
